export const accountsStrings = {
  title: 'Sosyal Hesaplar',
  subtitle: 'Bağlı sosyal medya hesaplarınızı yönetin',
  connect: 'Hesap Bağla',
  refresh: 'Yenile',
  refreshing: 'Güncelleniyor...',
  loading: 'Hesaplar yükleniyor...',
  empty: 'Henüz bağlı hesap yok.',
  loadError: 'Hesaplar yüklenemedi.',
  connectError: 'Bağlantı başlatılamadı.',
  deleteError: 'Hesap kaldırılamadı.',
  removeConfirmTitle: 'Hesabı kaldır',
  removeConfirmMessage: 'Bu hesabın bağlantısını kaldırmak istiyor musunuz?',
  cancel: 'Vazgeç',
  remove: 'Kaldır',
  followers: 'takipçi',
  connected: 'Bağlı',
  modalTitle: 'Platform seçin',
  modalClose: 'Kapat',
  oauthHint:
    'OAuth akışı tarayıcıda açılır; bu sürümde mobilden başlatma yakında.',
  accountCount: '{count} hesap bağlı',
  noToken: 'Oturum bulunamadı, lütfen tekrar giriş yapın.',
  stats: {
    totalAccounts: 'Toplam Hesap',
    totalFollowers: 'Toplam Takipçi',
    platforms: 'Platform',
  },
  group: {
    instagram: 'Instagram Hesapları',
    facebook: 'Facebook Hesapları',
    youtube: 'YouTube Hesapları',
    tiktok: 'TikTok Hesapları',
    social: 'Diğer Hesaplar',
  },
  platform: {
    instagram: 'Instagram',
    instagramSub: 'Meta / Facebook ile giriş',
    facebook: 'Facebook',
    facebookSub: 'Sayfa veya profil',
    youtube: 'YouTube',
    youtubeSub: 'Kanal',
    tiktok: 'TikTok',
    tiktokSub: 'İçerik üreticisi hesabı',
  },
};
