export const calendarStrings = {
  title: 'Takvim',
  subtitle: 'Planlı gönderilerinizi izleyin',
  loading: 'Planlı gönderiler yükleniyor...',
  empty: 'Henüz planlı gönderi yok.',
  when: 'Planlanan zaman',
  publishedWhen: 'Yayın zamanı',
  accounts: 'Hedef hesaplar',
  detailTitle: 'Plan Detayı',
  save: 'Güncelle',
  saving: 'Kaydediliyor...',
  delete: 'Sil',
  deleting: 'Siliniyor...',
  cancel: 'Vazgeç',
  close: 'Kapat',
  updated: 'Planlı gönderi güncellendi.',
  deleted: 'Planlı gönderi silindi.',
  updateError: 'Güncelleme yapılamadı.',
  deleteError: 'Silme işlemi başarısız.',
  loadError: 'Veriler yüklenemedi.',
  viewAll: 'Tümünü görüntüle',
  showLess: 'Daha az göster',
  prevMonth: 'Önceki ay',
  nextMonth: 'Sonraki ay',
  postsOnDay: 'Bu güne planlanan gönderiler',
  selectDay: 'Bir gün seçin',
  noPostsForDay: 'Bu gün için planlı gönderi yok.',
  removeConfirmTitle: 'Planı sil',
  removeConfirmMessage: 'Bu planlı gönderiyi silmek istiyor musunuz?',
  fields: {
    title: 'Başlık',
    caption: 'Açıklama',
    hashtags: 'Hashtag',
    date: 'Tarih (YYYY-AA-GG)',
    time: 'Saat (SS:DD)',
  },
  errors: {
    scheduleRequired: 'Tarih ve saat zorunlu.',
    scheduleFormat: 'Tarih YYYY-AA-GG, saat SS:DD biçiminde olmalı.',
    scheduleFuture: 'Planlama tarihi geçmişte olamaz.',
    captionRequired: 'Açıklama boş olamaz.',
    accountRequired: 'En az bir hesap seçmelisiniz.',
  },
  sections: {
    planned: 'Planlanan Gönderiler',
    history: 'Planlanmış ve Paylaşılmış',
  },
  status: {
    SCHEDULED: 'Planlandı',
    PROCESSING: 'İşleniyor',
    SUCCESS: 'Başarılı',
    FAILED: 'Başarısız',
    PARTIAL: 'Kısmi başarı',
  } as Record<string, string>,
  monthNames: [
    'Ocak',
    'Şubat',
    'Mart',
    'Nisan',
    'Mayıs',
    'Haziran',
    'Temmuz',
    'Ağustos',
    'Eylül',
    'Ekim',
    'Kasım',
    'Aralık',
  ],
  weekDayShort: ['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'],
};
