export const createStrings = {
  title: 'Gönderi Oluştur',
  subtitle: 'İçeriğinizi seçilen hesaplarda hemen paylaşın veya planlayın.',
  loadingAccounts: 'Hesaplar yükleniyor...',
  emptyAccounts: 'Bağlı hesap bulunamadı',
  emptyAccountsSub: 'Paylaşım için önce en az bir sosyal hesabı bağlayın.',
  goAccounts: 'Hesaplara git',
  sections: {
    details: 'Gönderi Detayları',
    detailsSub: 'Gönderi içeriğinizi hazırlayın',
    media: 'Medya',
    mediaSub: 'Instagram için foto veya video seçin',
    accounts: 'Hesapları Seç',
    accountsSub: 'Gönderinin paylaşılacağı hesapları seçin',
    actions: 'Aksiyonlar',
    schedule: 'Zamanlama',
    scheduleSub: 'Gönderiyi ileri bir tarihe planlayın',
    history: 'Geçmiş',
  },
  fields: {
    title: 'Başlık',
    caption: 'Açıklama',
    hashtags: 'Hashtag',
    date: 'Tarih (YYYY-AA-GG)',
    time: 'Saat (SS:DD)',
    titlePlaceholder: 'Gönderi başlığını girin',
    captionPlaceholder: 'Açıklama yazın...',
    hashtagsPlaceholder: '#hashtag #influencehub',
    datePlaceholder: '2026-04-30',
    timePlaceholder: '14:30',
  },
  actions: {
    publishNow: 'Şimdi Paylaş',
    schedule: 'Sonra Paylaş',
    publishing: 'Paylaşılıyor...',
    scheduling: 'Planlanıyor...',
  },
  media: {
    select: 'Galeriden Seç',
    camera: 'Kameradan Çek',
    remove: 'Kaldır',
    hint: 'Instagram paylaşımı için en az bir medya zorunludur. Maks. 15 MB / dosya.',
  },
  errors: {
    contentRequired: 'En az başlık veya açıklama girmelisiniz.',
    accountRequired: 'En az bir hesap seçmelisiniz.',
    mediaRequiredInstagram:
      'Instagram seçildiyse foto veya video zorunludur.',
    scheduleRequired: 'Planlama için tarih ve saat zorunlu.',
    scheduleFuture: 'Planlama tarihi geçmişte olamaz.',
    scheduleFormat: 'Tarih YYYY-AA-GG, saat SS:DD biçiminde olmalı.',
  },
  feedback: {
    published: 'Gönderi başarıyla paylaşıldı.',
    scheduled: 'Gönderi planlandı.',
    error: 'İşlem başarısız oldu.',
    network: 'Ağ hatası. Lütfen tekrar deneyin.',
    tooLarge: 'Seçilen medya çok büyük. Daha küçük bir dosya deneyin.',
  },
  history: {
    empty: 'Henüz gönderi geçmişi yok.',
    when: 'Zaman',
    accounts: 'Hesaplar',
  },
  status: {
    SCHEDULED: 'Planlandı',
    PROCESSING: 'İşleniyor',
    SUCCESS: 'Başarılı',
    FAILED: 'Başarısız',
    PARTIAL: 'Kısmi başarı',
  } as Record<string, string>,
};
