export const dashboardStrings = {
  welcome: 'Tekrar hoş geldiniz!',
  title: 'Panel',
  subtitle: 'İçerik performansınıza genel bakış',
  role: 'İçerik Üreticisi',
  logout: 'Çıkış',
  notifications: 'Bildirimler',
  menuTitle: 'Menü',
  closeMenu: 'Menüyü kapat',
  openMenu: 'Menüyü aç',
  nav: {
    dashboard: 'Panel',
    accounts: 'Hesaplar',
    createPost: 'Gönderi Oluştur',
    calendar: 'Takvim',
    analytics: 'Analitik',
    aiAssistant: 'Yapay Zeka Asistanı',
    settings: 'Ayarlar',
  },
  stats: {
    connectedAccounts: 'Bağlı Hesaplar',
    connectedAccountsHint: 'Tüm platformlar',
    publishedPosts: 'Yayınlanan Gönderiler',
    publishedPostsHint: 'Toplam yayın',
    scheduledPosts: 'Zamanlanmış Gönderiler',
    scheduledPostsHint: 'Yaklaşan gönderiler',
    avgEngagement: 'Ort. Etkileşim',
    avgEngagementHint: 'Gönderi başına',
  },
  charts: {
    recentEngagement: 'Son Gönderi Etkileşimi',
    aiTimes: 'Yapay Zeka Önerilen Paylaşım Saatleri',
    sampleTime: 'En iyi saat: Pazartesi 08:00',
    sampleDesc: 'Kitlenize göre daha fazla erişim beklenebilir.',
    samplePct: '%60',
  },
  comingSoon: 'Bu bölüm yakında.',
  logoutConfirmTitle: 'Çıkış yap',
  logoutConfirmMessage: 'Oturumunuzu kapatmak istiyor musunuz?',
  cancel: 'Vazgeç',
};
